version: '3.8'
services:
  pg:
    image: postgres:13-alpine
    container_name: tsdip-pg
    environment:
      - POSTGRES_USER=tsdip
      - POSTGRES_PASSWORD=tsdip
      - POSTGRES_DB=tsdip
    ports:
      - 5432:5432
    networks:
      - tsdip
    volumes:
      - tsdip-db:/var/lib/postgresql/data

  api:
    build: .
    image: tsdip-api
    container_name: tsdip-api
    env_file: .env
    ports:
      - 5000:5000
    networks:
      - tsdip
    volumes:
      - ./:/usr/app
    depends_on:
      - pg

networks:
  tsdip:
    name: tsdip-network

volumes:
  tsdip-db:
    name: tsdip-db
