apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: tsdip-api

build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
    - image: tsdip-api

deploy:
  kustomize:
    paths:
      - k8s/base

profiles:
  - name: staging
    deploy:
      kustomize:
        paths:
          - k8s/overlays/staging
