name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u USERNAME -p GITHUB_TOKEN
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/Taiwolkit/tsdip-api/tsdip-api:{{GITHUB_REF}}
      - name: publish docker image to Github package registry
        run: docker push docker.pkg.github.com/Taiwolkit/tsdip-api/tsdip-api:{{GITHUB_REF}}
