name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.12.5
